// Generates worker/src/catalog.js from ../index.html — the single source of
// truth for both the track list and the scene map. Run this whenever
// SP_TRACKS or the top-nav goScene() links change; never hand-edit
// catalog.js directly, it'll just get overwritten.
//
//   node scripts/gen-catalog.mjs
//
// Track catalog source: the SP_TRACKS array (the real, site-wide jukebox —
// NOT the smaller/mostly-placeholder TRACKS array used by the Transmissions
// scene player).
// Scene catalog source: the top-nav .tb-link elements, each of which already
// pairs a goScene(N) call with its own human-readable label — the same
// element a visitor clicks, so it can't drift from the real nav.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexPath = join(__dirname, '..', '..', 'index.html');
const outPath = join(__dirname, '..', 'src', 'catalog.js');

const html = readFileSync(indexPath, 'utf8');

// ── Tracks: pull the SP_TRACKS array literal, then every {title:'...'} ─────
const spMatch = html.match(/const SP_TRACKS=\[([\s\S]*?)\n\];/);
if (!spMatch) throw new Error('SP_TRACKS array not found in index.html — did it get renamed?');
const trackTitles = [...spMatch[1].matchAll(/title:\s*(['"])((?:\\.|(?!\1).)*)\1/g)]
  .map((m) => m[2].replace(/\\(['"\\])/g, '$1'));
if (!trackTitles.length) throw new Error('Parsed SP_TRACKS but found zero titles — regex likely out of sync with the array format.');

// ── Scenes: HOME (tb-brand, always 0) + each .tb-link's goScene(N) + label ─
const scenes = [{ index: 0, name: 'HOME' }];
const navRe = /<a[^>]*class="tb-link[^"]*"[^>]*onclick="goScene\((\d+)\)[^"]*"[^>]*>(.*?)<\/a>/g;
for (const m of html.matchAll(navRe)) {
  const index = Number(m[1]);
  const label = m[2].replace(/<span class="n">\d+<\/span>/, '').replace(/<[^>]+>/g, '').trim(); // strip the "NN" index prefix span
  if (label && !scenes.some((s) => s.index === index)) scenes.push({ index, name: label });
}
scenes.sort((a, b) => a.index - b.index);
if (scenes.length < 2) throw new Error('Found HOME but no nav scene links — did the top nav markup change?');

// ── Links: the ACCESS scene's .llinks block — real socials/store/support ───
// links, same ones a visitor sees and clicks, so open_link can't be pointed
// anywhere the site itself doesn't already link to.
const llinksMatch = html.match(/<div class="llinks">([\s\S]*?)<div class="lform">/);
if (!llinksMatch) throw new Error('.llinks block not found in the ACCESS scene — did it get restructured?');
const links = [...llinksMatch[1].matchAll(/<a href="([^"]+)"[^>]*class="lrow"[^>]*>([^<]+)</g)].map((m) => {
  const key = m[2].trim().split(/\s*\/\s*/)[0].replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase();
  return { key, url: m[1] };
});
if (!links.length) throw new Error('Parsed .llinks but found zero <a class="lrow"> entries.');

const banner = `// GENERATED by worker/scripts/gen-catalog.mjs from ../index.html — do not hand-edit.\n// Re-run that script after changing SP_TRACKS, the top-nav goScene() links, or the ACCESS scene's .llinks.\n`;
const body =
  `export const TRACK_TITLES = ${JSON.stringify(trackTitles, null, 2)};\n\n` +
  `export const SCENES = ${JSON.stringify(scenes, null, 2)};\n\n` +
  `export const LINKS = ${JSON.stringify(links, null, 2)};\n`;

writeFileSync(outPath, banner + '\n' + body);
console.log(`catalog.js written: ${trackTitles.length} tracks, ${scenes.length} scenes, ${links.length} links.`);
