// GENERATED by worker/scripts/gen-catalog.mjs from ../index.html — do not hand-edit.
// Re-run that script after changing SP_TRACKS, the top-nav goScene() links, or the ACCESS scene's .llinks.

export const TRACK_TITLES = [
  "AHS - PALESTINE",
  "DIVESTA",
  "BAZANTAR / HANCOCK",
  "MALCOLM X / LIBS",
  "A.I. BABY",
  "BASICK WAR DANCE",
  "EXILED / MARCOS",
  "ICE COLD FEAR",
  "JORDAN MAXWELL FOOTSIES",
  "HEDGES 2026",
  "MR ROBOT INTRO",
  "I DON'T HAVE A SHADOW ANYMORE",
  "3EAS - JULY 18 2026",
  "3EAS - CAN'T SMELL YOU",
  "3EAS - DO YOU FUCK YOUR CHATBOT",
  "3EAS - LATE NIGHT CALLS",
  "3EAS - WOMEN AND CHILDREN",
  "3EAS - ICE COLD MURDER",
  "3EAS - CUBIC ZIRCONIA",
  "RITCHIE CURANDERO",
  "3EAS - DRAW BLOOD FOR SPRING",
  "3EAS - LITTLE FAITH, IT'S IN THE DENIAL",
  "3EAS - ANALYSIS AND ASSESSMENT OF GATEWAY PROCESS (DECLASSIFIED)",
  "3EAS - PAJARITOS PARA TI",
  "3EAS - RIVER VIPER",
  "3EAS - CRAVINGS 2012",
  "3EAS - A MOMENT BY RITA"
];

export const SCENES = [
  {
    "index": 0,
    "name": "HOME"
  },
  {
    "index": 1,
    "name": "TRANSMISSIONS"
  },
  {
    "index": 2,
    "name": "VISUALS"
  },
  {
    "index": 3,
    "name": "ACQUISITIONS"
  },
  {
    "index": 4,
    "name": "DISPATCH"
  },
  {
    "index": 5,
    "name": "LAB"
  },
  {
    "index": 6,
    "name": "SIGNAL"
  },
  {
    "index": 7,
    "name": "ACCESS"
  }
];

export const LINKS = [
  {
    "key": "MIXCLOUD",
    "url": "https://www.mixcloud.com/SELEXIONES/"
  },
  {
    "key": "INSTAGRAM",
    "url": "https://instagram.com/zo.losangeles"
  },
  {
    "key": "SELEXIONES_COM",
    "url": "https://selexiones.com"
  },
  {
    "key": "ONNOTICEMUSIC_COM",
    "url": "https://www.onnoticemusic.com/"
  },
  {
    "key": "SACREDLESSONS_COM",
    "url": "https://sacredlessons.com"
  },
  {
    "key": "WORLDOFMUSICSHOP_COM",
    "url": "https://worldofmusicshop.com"
  },
  {
    "key": "DONATE",
    "url": "https://ko-fi.com/3eascortex"
  }
];
